image: docker:stable

stages:
  - build
  - publish
  - deploy

docker build:
  stage: build
  before_script:
  - docker version
  - "docker info"
  script:
  - docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH} --pull .

Push to gitlab container registry:
  stage: publish
  before_script:
    - docker version
    - "docker info"
    - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"
  script:
    - "docker build -t ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest --pull ."
    - "docker push ${CI_REGISTRY}/${CI_PROJECT_PATH}:latest"
  after_script:
    - "docker logout ${CI_REGISTRY}"
  script:
  - "docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $CI_REGISTRY"

deploy_prod:
  stage: deploy
  script:
    - echo "Deploy to production server using ansible"
  environment:
    name: production
    url: https://z720.net
  when: manual


  